return {
    "000_no_loop.lua",
    "001_full_start_continuous.lua",
    "002_offset_continuous_reference.lua",
    "003_offset_until_release.lua",
    "004_offset_continuous_loopselect_1.lua",
    "005_offset_playback_mode_1.lua",
    "006_offset_playback_mode_2.lua",
    "007_offset_playback_mode_3.lua",
    "008_offset_loop_start_minus_1.lua",
    "009_offset_loop_start_plus_1.lua",
    "010_offset_loop_end_literal.lua",
    "011_offset_loop_end_plus_2.lua",
    "012_until_release_release_start_tail.lua",
    "013_mode_5_offset.lua",
    "014_current_helper_truncated.lua",
}
