local hb = require("halionbridge-sfz")

local layerName = "004 Transpose Plus 12"
local outputFile = "004_transpose_plus_12.vstpreset"

-- This file was generated by halionbridge convert sfz. Region data is
-- grouped by source concern so converter authors can inspect the SFZ
-- sample playback, mapping, envelope, and optional tone fields before
-- HALion saves the preset.
local regions = {
    {
        name = "sine_A3_single_cycle",
        sample_playback = {
            sample = "C:/develop/halionbridge/probes/sfz/026-static-pitch-keytrack-centerkey-regression/source/samples/sine_A3_single_cycle.wav",
        },
        mapping = {
            key_low = 48,
            key_high = 84,
            velocity_low = 0,
            velocity_high = 127,
            root_key = 57,
        },
        amp_envelope = {
            points = {
                { level = 0, duration = 0, curve = 0 },
                { level = 1, duration = 0.00100000005, curve = 0 },
                { level = 1, duration = 0, curve = 0 },
                { level = 0, duration = 0.0500000007, curve = 0 },
            },
            sustain_index = 3,
        },
        pitch = {
            tune_cents = 1200,
        },
        loop = {
            start = 0,
            finish = 199,
        },
        gain = {
            amp_velocity_to_level = 100,
        },
    },
}

return function(ctx)
    ctx.log("Building " .. layerName)

    local layer, layerErr = hb.create_layer(ctx, layerName)
    if not layer then
        return hb.fail(layerErr)
    end

    for i, region in ipairs(regions) do
        local label = hb.region_label(region)
        ctx.progress(i - 1, #regions, "Mapping " .. label)
        local zone, zoneErr = hb.append_sample_zone(ctx, layer, region)
        if not zone then
            return hb.fail(zoneErr)
        end
        ctx.progress(i, #regions, "Mapped " .. label)
    end

    ctx.progress(#regions, #regions + 1, "Saving " .. outputFile)
    local saved, saveErr = hb.save_layer_preset(ctx, layer, outputFile)
    if not saved then
        return hb.fail(saveErr)
    end

    ctx.progress(#regions + 1, #regions + 1, "Saved " .. outputFile)
    return hb.ok("Built " .. outputFile, 1)
end
