local hb = require("halionbridge-sfz")

local layerName = "000 Synth Single Cycle Six Regions"
local outputFile = "000_synth_single_cycle_six_regions.vstpreset"

-- This file was generated by halionbridge convert sfz. Region data is
-- grouped by source concern so converter authors can inspect the SFZ
-- sample playback, mapping, envelope, and optional tone fields before
-- HALion saves the preset.
local regions = {
    {
        name = "saw_A3_single_cycle",
        sample_playback = {
            sample = "C:/develop/halionbridge/probes/sfz/022-synth-single-cycle-regression/source/samples/saw_A3_single_cycle.wav",
        },
        mapping = {
            key_low = 36,
            key_high = 43,
            velocity_low = 0,
            velocity_high = 127,
            root_key = 57,
        },
        amp_envelope = {
            points = {
                { level = 0, duration = 0, curve = 0 },
                { level = 1, duration = 0.000999941956, curve = 0 },
                { level = 1, duration = 0, curve = 0 },
                { level = 0, duration = 0.00100000005, curve = 0 },
            },
            sustain_index = 3,
        },
        loop = {
            start = 0,
            finish = 199,
        },
        gain = {
            amp_velocity_to_level = 100,
        },
        filter = {
            cutoff = 4978,
        },
    },
    {
        name = "additive_organ_A3_si",
        sample_playback = {
            sample = "C:/develop/halionbridge/probes/sfz/022-synth-single-cycle-regression/source/samples/additive_organ_A3_si.wav",
        },
        mapping = {
            key_low = 44,
            key_high = 51,
            velocity_low = 0,
            velocity_high = 127,
            root_key = 57,
        },
        amp_envelope = {
            points = {
                { level = 0, duration = 0, curve = 0 },
                { level = 1, duration = 0.000999941956, curve = 0 },
                { level = 1, duration = 0, curve = 0 },
                { level = 0, duration = 0.00100000005, curve = 0 },
            },
            sustain_index = 3,
        },
        loop = {
            start = 0,
            finish = 199,
        },
        gain = {
            amp_velocity_to_level = 100,
        },
        filter = {
            cutoff = 4978,
        },
    },
    {
        name = "sine_A3_single_cycle",
        sample_playback = {
            sample = "C:/develop/halionbridge/probes/sfz/022-synth-single-cycle-regression/source/samples/sine_A3_single_cycle.wav",
        },
        mapping = {
            key_low = 52,
            key_high = 59,
            velocity_low = 0,
            velocity_high = 127,
            root_key = 57,
        },
        amp_envelope = {
            points = {
                { level = 0, duration = 0, curve = 0 },
                { level = 1, duration = 0.000999941956, curve = 0 },
                { level = 1, duration = 0, curve = 0 },
                { level = 0, duration = 0.00100000005, curve = 0 },
            },
            sustain_index = 3,
        },
        loop = {
            start = 0,
            finish = 199,
        },
        gain = {
            amp_velocity_to_level = 100,
        },
        filter = {
            cutoff = 4978,
        },
    },
    {
        name = "pulse25_A3_single_cy",
        sample_playback = {
            sample = "C:/develop/halionbridge/probes/sfz/022-synth-single-cycle-regression/source/samples/pulse25_A3_single_cy.wav",
        },
        mapping = {
            key_low = 60,
            key_high = 67,
            velocity_low = 0,
            velocity_high = 127,
            root_key = 57,
        },
        amp_envelope = {
            points = {
                { level = 0, duration = 0, curve = 0 },
                { level = 1, duration = 0.000999941956, curve = 0 },
                { level = 1, duration = 0, curve = 0 },
                { level = 0, duration = 0.00100000005, curve = 0 },
            },
            sustain_index = 3,
        },
        loop = {
            start = 0,
            finish = 199,
        },
        gain = {
            amp_velocity_to_level = 100,
        },
        filter = {
            cutoff = 4978,
        },
    },
    {
        name = "triangle_A3_single_c",
        sample_playback = {
            sample = "C:/develop/halionbridge/probes/sfz/022-synth-single-cycle-regression/source/samples/triangle_A3_single_c.wav",
        },
        mapping = {
            key_low = 68,
            key_high = 75,
            velocity_low = 0,
            velocity_high = 127,
            root_key = 57,
        },
        amp_envelope = {
            points = {
                { level = 0, duration = 0, curve = 0 },
                { level = 1, duration = 0.000999941956, curve = 0 },
                { level = 1, duration = 0, curve = 0 },
                { level = 0, duration = 0.00100000005, curve = 0 },
            },
            sustain_index = 3,
        },
        loop = {
            start = 0,
            finish = 199,
        },
        gain = {
            amp_velocity_to_level = 100,
        },
        filter = {
            cutoff = 4978,
        },
    },
    {
        name = "sample_hold_A3_singl",
        sample_playback = {
            sample = "C:/develop/halionbridge/probes/sfz/022-synth-single-cycle-regression/source/samples/sample_hold_A3_singl.wav",
        },
        mapping = {
            key_low = 76,
            key_high = 82,
            velocity_low = 0,
            velocity_high = 127,
            root_key = 57,
        },
        amp_envelope = {
            points = {
                { level = 0, duration = 0, curve = 0 },
                { level = 1, duration = 0.000999941956, curve = 0 },
                { level = 1, duration = 0, curve = 0 },
                { level = 0, duration = 0.00100000005, curve = 0 },
            },
            sustain_index = 3,
        },
        loop = {
            start = 0,
            finish = 199,
        },
        gain = {
            amp_velocity_to_level = 100,
        },
        filter = {
            cutoff = 4978,
        },
    },
}

return function(ctx)
    ctx.log("Building " .. layerName)

    local layer, layerErr = hb.create_layer(ctx, layerName)
    if not layer then
        return hb.fail(layerErr)
    end

    for i, region in ipairs(regions) do
        local label = hb.region_label(region)
        ctx.progress(i - 1, #regions, "Mapping " .. label)
        local zone, zoneErr = hb.append_sample_zone(ctx, layer, region)
        if not zone then
            return hb.fail(zoneErr)
        end
        ctx.progress(i, #regions, "Mapped " .. label)
    end

    ctx.progress(#regions, #regions + 1, "Saving " .. outputFile)
    local saved, saveErr = hb.save_layer_preset(ctx, layer, outputFile)
    if not saved then
        return hb.fail(saveErr)
    end

    ctx.progress(#regions + 1, #regions + 1, "Saved " .. outputFile)
    return hb.ok("Built " .. outputFile, 1)
end
