if(NOT DEFINED HALIONBRIDGE_CLI)
    message(FATAL_ERROR "HALIONBRIDGE_CLI is required.")
endif()

if(NOT DEFINED HALIONBRIDGE_EXPECT_EXIT)
    message(FATAL_ERROR "HALIONBRIDGE_EXPECT_EXIT is required.")
endif()

if(DEFINED HALIONBRIDGE_ARGS)
    string(REPLACE "|" ";" HALIONBRIDGE_COMMAND_ARGS "${HALIONBRIDGE_ARGS}")
else()
    set(HALIONBRIDGE_COMMAND_ARGS)
endif()

if(NOT DEFINED HALIONBRIDGE_WORKING_DIRECTORY)
    set(HALIONBRIDGE_WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}")
endif()

execute_process(
    COMMAND "${HALIONBRIDGE_CLI}" ${HALIONBRIDGE_COMMAND_ARGS}
    WORKING_DIRECTORY "${HALIONBRIDGE_WORKING_DIRECTORY}"
    RESULT_VARIABLE HALIONBRIDGE_ACTUAL_EXIT
    OUTPUT_VARIABLE HALIONBRIDGE_STDOUT
    ERROR_VARIABLE HALIONBRIDGE_STDERR
)

set(HALIONBRIDGE_OUTPUT "${HALIONBRIDGE_STDOUT}${HALIONBRIDGE_STDERR}")

if(NOT HALIONBRIDGE_ACTUAL_EXIT EQUAL HALIONBRIDGE_EXPECT_EXIT)
    message(FATAL_ERROR
        "Expected exit ${HALIONBRIDGE_EXPECT_EXIT}, got ${HALIONBRIDGE_ACTUAL_EXIT}.\n"
        "Command: ${HALIONBRIDGE_CLI} ${HALIONBRIDGE_COMMAND_ARGS}\n"
        "Output:\n${HALIONBRIDGE_OUTPUT}"
    )
endif()

if(DEFINED HALIONBRIDGE_EXPECT_REGEX AND NOT HALIONBRIDGE_OUTPUT MATCHES "${HALIONBRIDGE_EXPECT_REGEX}")
    message(FATAL_ERROR
        "Expected output to match: ${HALIONBRIDGE_EXPECT_REGEX}\n"
        "Command: ${HALIONBRIDGE_CLI} ${HALIONBRIDGE_COMMAND_ARGS}\n"
        "Output:\n${HALIONBRIDGE_OUTPUT}"
    )
endif()

if(DEFINED HALIONBRIDGE_REJECT_REGEX AND HALIONBRIDGE_OUTPUT MATCHES "${HALIONBRIDGE_REJECT_REGEX}")
    message(FATAL_ERROR
        "Expected output not to match: ${HALIONBRIDGE_REJECT_REGEX}\n"
        "Command: ${HALIONBRIDGE_CLI} ${HALIONBRIDGE_COMMAND_ARGS}\n"
        "Output:\n${HALIONBRIDGE_OUTPUT}"
    )
endif()
