local hb = require("halionbridge-sfz")

local layerName = "002 Loop Continuous Offset To Loop"
local outputFile = "002_loop_continuous_offset_to_loop.vstpreset"

-- This file was generated by halionbridge convert sfz. Region data is
-- grouped by source concern so converter authors can inspect the SFZ
-- sample playback, mapping, envelope, and optional tone fields before
-- HALion saves the preset.
local regions = {
    {
        name = "pre_loop_tail_clean",
        sample_playback = {
            sample = "C:/develop/halionbridge/probes/sfz/042-loop-mode-implementation-regression/source/samples/pre_loop_tail_clean.wav",
            offset = 11000,
            natural_end = 154099,
        },
        mapping = {
            key_low = 57,
            key_high = 57,
            velocity_low = 0,
            velocity_high = 127,
            root_key = 57,
        },
        amp_envelope = {
            points = {
                { level = 0, duration = 0, curve = 0 },
                { level = 1, duration = 0, curve = 0 },
                { level = 1, duration = 0, curve = 0 },
                { level = 0, duration = 3, curve = 0 },
            },
            sustain_index = 3,
        },
        loop = {
            mode = "continuous",
            start = 11000,
            finish = 21999,
        },
        gain = {
            sample_osc_level_db = 7.80000019,
            amp_velocity_to_level = 100,
        },
    },
}

return function(ctx)
    ctx.log("Building " .. layerName)

    local layer, layerErr = hb.create_layer(ctx, layerName)
    if not layer then
        return hb.fail(layerErr)
    end

    for i, region in ipairs(regions) do
        local label = hb.region_label(region)
        ctx.progress(i - 1, #regions, "Mapping " .. label)
        local zone, zoneErr = hb.append_sample_zone(ctx, layer, region)
        if not zone then
            return hb.fail(zoneErr)
        end
        ctx.progress(i, #regions, "Mapped " .. label)
    end

    ctx.progress(#regions, #regions + 1, "Saving " .. outputFile)
    local saved, saveErr = hb.save_layer_preset(ctx, layer, outputFile)
    if not saved then
        return hb.fail(saveErr)
    end

    ctx.progress(#regions + 1, #regions + 1, "Saved " .. outputFile)
    return hb.ok("Built " .. outputFile, 1)
end
